export const REMOVE_ORIGIN = 'REMOVE_ORIGIN';
export const REMOVE_DESTINATION = 'REMOVE_DESTINATION';
export const UPDATE_ORIGIN = 'UPDATE_ORIGIN';
export const UPDATE_DESTINATION = 'UPDATE_DESTINATION';
export const SET_TRAVEL_MODE = 'SET_TRAVEL_MODE';
